name: Action
on:
  push:
    branches:
    - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}   

    - name: pull docker image
      run: docker pull dishoneprabu/j2dk:j2dk.in

    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.19.0
      with:
        image-ref: dishoneprabu/j2dk:j2dk.in
        format: (@/contrib/junit.tpl)
        output: ./report.xml


    
