name: Action
on:
  push:
    branches:
    - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}   

    - name: pull docker image
      run: docker pull dishoneprabu/j2dk:j2dk.in

    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.19.0
      with:
        image-ref: dishoneprabu/j2dk:j2dk.in
        format: template
        template: "@/contrib/junit.tpl"
        output: ./report.xml
        
    - name: Upload the trivy Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: trivy-report
        path: ./report.xml
        
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        login-server: azurecontinerregistery.azurecr.io

    - name: Push docker image
      run: |
        docker tag dishoneprabu/j2dk:j2dk.in azurecontinerregistery.azurecr.io/j2dk:j2dk.in
        docker push azurecontinerregistery.azurecr.io/j2dk:j2dk.in


    
