name: Kubernetes
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions: 
    id-token: write
    contents: read
    actions: read
  
jobs:
  CICD:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    

    - name: 'Az CLI login'
      uses: Azure/login@v2.0.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    # - name: find path
    #   run: |
    #     ls -a
    #     pwd
    #     cp /home/runner/work/git-action/git-action/deployment.yaml /tmp/deployment.yaml
    
    - uses: azure/setup-kubectl@v4    

    - name: Set Kubernetes Context
      uses: azure/aks-set-context@v4
      with:
        cluster-name: 'kubernetes-cluster'
        resource-group: 'kubernetes'

    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v4.9
      with:
        namespace: apps
        manifests: |
          deployment.yaml
        images: 'nginx:mainline-bookworm-perl'
