name: webhook-trigger-Job
# on: 
#   repository_dispatch:
#       types: [*]

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person'
        required: true
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: trigger
#       uses: peter-evans/repository-dispatch@v3.0.0
#       with:
#         token: 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
#         repository: dishoneprabu/git-action
#         event-type:  my-event
#         client-payload: '{"github": ${{ toJson(github) }}}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker image
      run: |
        echo "Hello World"
        env
        echo ${{ toJson(github.event.client_payload }}

        
