name: ZAP Scan

on:
  workflow_dispatch:
    inputs:
      scan:
        description: "Enable Full Scan"
        type: boolean
        required: true
      # scan_type:
      #   description: "Baseline or Full scan"
      #   required: true
      #   type: choice
      #   options:
      #     - "Full"
      #     - "Baseline"
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  
jobs:
  Scan:
    runs-on: ubuntu-latest
    name: Scan on QA
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: ZAP Full Scan
        if: github.event.inputs.scan == true
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: ${{ vars.SCAN_URL }}
          
      - name: ZAP Baseline Scan
        if: github.event.inputs.scan == false
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ vars.SCAN_URL }}

