name: ZAP Scan

on:
  workflow_dispatch:
    inputs:
      # url:
      #   description: "Web URL"
      #   required: true
      # scan_type:
      #   description: "Baseline or Full scan"
      #   required: true
      #   type: choice
      #   options:
      #     - "Full"
      #     - "Baseline"
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  
jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: |
          env

      # - name: ZAP Full Scan
      #   uses: zaproxy/action-full-scan@v0.10.0
      #   with:
      #     target: 'https://j2dk.in/'

