name: ZAP Scan

on:
  workflow_dispatch:
  
jobs:
  Scan:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - uses: actions/checkout@v3

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'https://j2dk.in/'

